## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import sys

def build(bld):
    obj = bld.create_ns3_program('simulator-main', ['node'])
    obj.source = [ 
        'simulator-main.cc',
        'ls-routing-protocol/ls-routing-protocol.cc',
        'ls-routing-protocol/ls-message.cc',
        'ls-routing-protocol/ls-routing-helper.cc',
        'dv-routing-protocol/dv-routing-protocol.cc',
        'dv-routing-protocol/dv-message.cc',
        'dv-routing-protocol/dv-routing-helper.cc',
        'test-app/test-app.cc',
        'test-app/test-app-message.cc',
        'test-app/test-app-helper.cc',
        'common/ping-request.cc',
        'common/penn-log.cc',
        'common/penn-routing-protocol.cc',
        'common/penn-application.cc',
        'common/test-result.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'upenn-cis553'
    headers.source = [
      'ls-routing-protocol/ls-routing-protocol.h',
      'ls-routing-protocol/ls-routing-helper.h',
      'ls-routing-protocol/ls-message.h',
      'dv-routing-protocol/dv-routing-protocol.h',
      'dv-routing-protocol/dv-routing-helper.h',
      'dv-routing-protocol/dv-message.h',
      'test-app/test-app.h',
      'test-app/test-app-message.h',
      'test-app/test-app-helper.h',
      'common/penn-log.h',
      'common/ping-request.h',
      'common/penn-routing-protocol.h',
      'common/penn-application.h',
      'common/test-result.h',
      ]
